### ISSUE TITLE
ESMPy installed but not module not found when imported

### ISSUE THREAD

**Issue by nuvolet** [esmf-org/esmf#137] opened 2023-05-03 18:27 UTC
Greetings,

I am newbie using this package. I followed all the instruction from the documentation and I think it has been "installed" under the environment requested.
When I activate the environment where the package has been installed I got this:
`$pip list
Package         Version
--------------- --------
cf-xarray       0.8.0
esmpy           8.4.2
exceptiongroup  1.1.1
iniconfig       2.0.0
llvmlite        0.39.1
numba           0.56.4
numpy           1.23.5
packaging       23.1
pandas          2.0.1
pip             23.1.2
pluggy          1.0.0
pytest          7.3.1
python-dateutil 2.8.2
pytz            2023.3
scipy           1.9.3
setuptools      67.7.2
shapely         2.0.1
six             1.16.0
sparse          0.14.0
tomli           2.0.1
tzdata          2023.3
wheel           0.40.0
xarray          2023.4.2
xesmf           0.7.1
`
While I import it in my script and run it I got this:

`Traceback (most recent call last):
  File "plot_regrid_CAM6_MATCH4.py", line 15, in <module>
    import esmpy
ModuleNotFoundError: No module named 'esmpy'`

For more info I use python3.8.

Anybody knows why although the package is in my environment is not found and imported properly.
Thanks I advance

Toni

**Comment by billsacks** [comment] 2023-05-04 19:46
This looks like a duplicate of a help request sent to esmf_support, which is our preferred mechanism for user support requests like this; I have addressed this issue via that mechanism.

**Closed by billsacks** 2023-05-04 19:46 UTC
